language: node_js
sudo: false
node_js:
  - 'iojs'
  
before_install:
  - npm install -g npm
 
script: npm run ci
  
branches:
  only:
    - master
    - d
	- sprint-3
	
notifications:
  email:
    on_success: never
    on_failure: never